# Copyright 2017, 2019, Oracle Corporation and/or affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

#cloud-config
timezone: ${timezone}

write_files:
# setup script
  - path: "/root/bastion/notification.sh"
    permissions: "0700"
    encoding: "gzip+base64"
    content: |
      ${notification_sh_content}
runcmd:
 - echo "Configuring running notification script..."
 - bash /root/bastion/notification.sh
 - touch /home/opc/bastion.finish