= Configuration

:idprefix:
:idseparator: -
:sectlinks:
:sectnums:

:uri-repo: https://github.com/oracle/terraform-oci-base

:uri-rel-file-base: link:{uri-repo}/blob/master
:uri-rel-tree-base: link:{uri-repo}/tree/master
:uri-docs: {uri-rel-file-base}/docs

:uri-changelog: {uri-rel-file-base}/CHANGELOG.adoc
:uri-contribute: {uri-rel-file-base}/CONTRIBUTING.adoc
:uri-contributors: {uri-rel-file-base}/CONTRIBUTORS.adoc
:uri-instructions: {uri-docs}/instructions.adoc
:uri-license: {uri-rel-file-base}/LICENSE.txt
:uri-networks-subnets-cidr: https://erikberg.com/notes/networks.html
:uri-oci: https://cloud.oracle.com/cloud-infrastructure
:uri-oci-documentation: https://docs.cloud.oracle.com/iaas/Content/home.htm
:uri-oci-instance-principal: https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/callingservicesfrominstances.htm
:uri-oci-region: https://docs.cloud.oracle.com/iaas/Content/General/Concepts/regions.htm
:uri-oracle: https://www.oracle.com
:uri-prereqs: {uri-docs}/prerequisites.adoc
:uri-quickstart: {uri-docs}/quickstart.adoc

:uri-terraform: https://www.terraform.io
:uri-terraform-cidrsubnet-desconstructed: http://blog.itsjustcode.net/blog/2017/11/18/terraform-cidrsubnet-deconstructed/
:uri-terraform-oci: https://www.terraform.io/docs/providers/oci/index.html
:uri-terraform-options: {uri-docs}/terraformoptions.adoc
:uri-topology: {uri-docs}/topology.adoc

. link:#assumptions[Assumptions]
. link:#configure-the-variable-file[Configure the variable file]
. link:#configure-identity-parameters[Configure identity parameters]
. link:#configure-ssh-keys[Configure ssh keys]
. link:#configure-oci-parameters[Configure OCI parameters]
. link:#configure-oci-networking-parameters[Configure OCI Networking parameters]
. link:#configure-bastion-host-parameters[Configure Bastion Host parameters]
. link:#configure-oke-parameters[Configure OKE parameters]
. link:#configure-oke-load-balancer-parameters[Configure OKE Load Balancer parameters]
. link:#configure-ocir-parameters[Configure OCIR parameters]
. link:#configure-helm-parameters[Configure helm parameters]
. link:#configure-calico-parameters[Configure Calico parameters]
. link:#configure-kubernetes-metrics-server-parameters[Configure Kubernetes Metrics Server parameters]

=== Assumptions

This section assumes you have completed all the {uri-prereqs}[pre-requisites].

=== Configure the variable file

A sample variable file (terraform.tfvars.example) with all the configuration options is available. Create a terraform variable file by copying the terraform.tfvars.example:

----
cp terraform.tfvars.example terraform.tfvars
----

=== Configure identity parameters

Enter the values for the following parameters in the terraform.tfvars file:

* api_fingerprint
* api_private_key_path
* compartment_name
* compartment_ocid
* tenancy_ocid
* user_ocid

e.g.

----
api_fingerprint = "1a:bc:23:45:6d:78:e9:f0:gh:ij:kl:m1:23:no:4p:5q"
----

You would have obtained your values when doing the {uri-prereqs}[pre-requisites]. 

{uri-terraform-options}#identity-and-access[Reference]

=== Configure ssh keys

If you intend to use the bastion host, you must supply the ssh keys:

----
ssh_private_key_path = "~/.ssh/id_rsa"

ssh_public_key_path = "~/.ssh/id_rsa.pub"
----

{uri-terraform-options}#ssh-keys[Reference]

=== Configure OCI parameters

The 2 OCI parameters here mainly concern:

* the label_prefix: this will append a string to the name of every resource created
* the region: this allows you to select the region where you want the OKE cluster deployed

e.g.

----
label_prefix="dev"
region="us-phoenix-1"
----

The list of regions can be found {uri-oci-region}[here].

{uri-terraform-options}#general-oci[Reference]

=== Configure OCI Networking parameters

The networking parameters concern the VCN and the subnets network configuration as well as whether to enable some specific features such as the NAT or the Service Gateways. 

You can leave most of the default options. However, you may want to change the following 2 parameters:

* vcn_dns_name: this is the internal dns domain for resources created
* vcn_name: this is the name of the vcn that will be appended to the label prefix

{uri-terraform-options}#oci-networking[Reference]

=== Configure bastion host parameters

The bastion host parameters concern whether you want to enable the bastion. 1 parameter to keep in mind here is the enable_instance_principal. Be aware that if this is enabled, it gives API access to the bastion host without authentication.

Read more about {uri-oci-instance-principal}[instance_principal].

{uri-terraform-options}#bastion-host[Reference]
