= Pre-requisites

:idprefix:
:idseparator: -
:sectlinks:

:uri-repo: https://github.com/oracle/terraform-oci-base

:uri-rel-file-base: link:{uri-repo}/blob/master
:uri-rel-tree-base: link:{uri-repo}/tree/master

:uri-docs: {uri-rel-file-base}/docs

:uri-oci: https://cloud.oracle.com/cloud-infrastructure
:uri-oci-compartment: https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingcompartments.htm#two
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five
:uri-oci-documentation: https://docs.cloud.oracle.com/iaas/Content/home.htm
:uri-oci-instance-principal: https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/callingservicesfrominstances.htm
:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#two
:uri-oci-keys-upload: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#two
:uri-quickstart: {uri-docs}/quickstart.adoc
:uri-terraform: https://www.terraform.io
:uri-terraform-download: https://www.terraform.io/downloads.html

This section documents the use of {uri-oci-instance-principal}[instance_principal] in the project.

. link:#using-instance_principal[Using instance_principal]
.. link:#enabling-instance_principal-on-the-bastion-host[Enabling instance_principal on the bastion host]
.. link:#disabling-instance_principal-on-the-bastion-host[Disabling instance_principal on the bastion host]
.. link:#recommendations-for-using-instance_principal[Recommendations for using instance_principal]


=== Using instance_principal

==== Enabling instance_principal on the admin host
{uri-oci-instance-principal}[instance_principal] is an IAM service feature that enables instances to be authorized actors (or principals) to perform actions on service resources. Each compute instance has its own identity, and it authenticates using the certificates that are added to it. These certificates are automatically created, assigned to instances and rotated, preventing the need for you to distribute credentials to your hosts and rotate them.

Any user who has access to the instance (who can SSH to the instance), automatically inherits the privileges granted to the instance. Before you enable this feature, ensure that you know who can access it, and that they should be authorized with the permissions you are granting to the instance.

By default, this feature is *_disabled_*.

When you enable this feature, by default, the admin host has privileges to manage all resources in the compartment. 

You can also turn on and off the feature at any time without impact on the admin host.

To enable, set enable_instance_principal in oci_base_admin to true:

----
oci_base_admin = {
  ....
  enable_instance_principal = true
  ....
}
----

and verify:

----
oci network vcn list --compartment-id <compartment-ocid>
----

You should be able to see a list of VCNs created in the compartment.

==== Disabling instance_principal on the admin host

To disable, set enable_instance_principal in oci_base_admin to false:

+
----
oci_base_admin = {
  ....
  enable_instance_principal = false
  ....
}
----

. Run terraform apply again:

+
----
terraform apply
----

==== Recommendations for using instance_principal

. Do not enable instance_principal if you are not using it
. Enable instance_principal *_if and only if_* you are using the admin host to execute oci commands e.g. modifying dynamic groups, changing policies
. Disable instance_principal once the oci operation is done