= Terraform Options
:idprefix:
:idseparator: -
:sectlinks:
:sectnums:
:uri-repo: https://github.com/oracle/terraform-oci-base

:uri-rel-file-base: link:{uri-repo}/blob/master
:uri-rel-tree-base: link:{uri-repo}/tree/master
:uri-docs: {uri-rel-file-base}/docs

:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five


This guide describes how to use the terraform-oci-base within your infrastructure project.

=== Assumptions

1. You have setup the {uri-oci-keys}[required keys]
2. You know the {uri-oci-ocids}[required OCIDs]

=== Pre-requisites

1. git is installed
2. ssh client is installed
3. Terraform 0.12.8+ is installed

=== Create a new Terraform project

As an example, we'll be using terraform-oci-base to create a gitlab infrastructure with the image from OCI Marketplace. The steps required are the following:

. Create a new directory for your project
. Create files in root directory
. Add the terraform-oci-base module

==== Create a new directory

. Open a terminal and create a new directory.

+
----
mkdir gitlab
cd gitlab
----

==== Create files in root directory

. Create the following files:
.. variables.tf
.. terraform.tfvars
.. locals.tf
.. provider.tf
.. main.tf

==== Add the terraform-oci-base module

. Create a modules directory
+
----
mkdir modules
cd modules
----

. Download the terraform-oci-base module
+
----
git clone https://github.com/oracle/terraform-oci-base.git base
----

. Define the base parameters in the root variables.tf. You can choose to keep the same object-oriented structure like in the base's variables.tf or keep it flat. Below is an example of flattening the variables:

+
----
# Identity and access parameters
variable "api_fingerprint" {
  description = "fingerprint of oci api private key"
}

variable "api_private_key_path" {
  description = "path to oci api private key"
}

variable "compartment_name" {
  type        = "string"
  description = "compartment name"
}

variable "compartment_ocid" {
  type        = "string"
  description = "compartment ocid"
}

variable "tenancy_ocid" {
  type        = "string"
  description = "tenancy id"
}

variable "user_ocid" {
  type        = "string"
  description = "user ocid"
}

# ssh keys
variable "ssh_private_key_path" {
  description = "path to ssh private key"
}

variable "ssh_public_key_path" {
  description = "path to ssh public key"
}

# general oci parameters
variable "disable_auto_retries" {
  default = true
}

variable "label_prefix" {
  type    = "string"
  default = "gitlab"
}

variable "region" {
  # List of regions: https://docs.cloud.oracle.com/iaas/Content/General/Concepts/regions.htm#ServiceAvailabilityAcrossRegions
  description = "region"
  default     = "us-phoenix-1"
}

# networking parameters
variable "newbits" {
  type        = "map"
  description = "new mask for the subnet within the virtual network. use as newbits parameter for cidrsubnet function"

  default = {
    bastion = 13
    lb      = 11
    gitlab = 2
  }
}

variable "vcn_cidr" {
  type        = "string"
  description = "cidr block of VCN"
  default     = "10.0.0.0/16"
}

variable "vcn_dns_label" {
  type    = "string"
  default = "gitlab"
}

variable "vcn_name" {
  type        = "string"
  description = "name of vcn"
  default     = "gitlab vcn"
}

# nat
variable "create_nat_gateway" {
  description = "whether to create a nat gateway"
  default     = true
}

variable "nat_gateway_name" {
  description = "display name of the nat gateway"
  default     = "nat"
}

# service gateway
variable "create_service_gateway" {
  description = "whether to create a service gateway"
  default     = true
}

variable "service_gateway_name" {
  description = "name of service gateway"
  default     = "sg"
}

variable "subnets" {
  description = "zero-based index of the subnet when the network is masked with the newbit."
  type        = "map"

  default = {
    bastion = 32
    pub_lb  = 16
    gitlab = 1
  }
}

# bastion
variable "bastion_shape" {
  description = "shape of bastion instance"
  default     = "VM.Standard.E2.1"
}

variable "create_bastion" {
  default = true
}

variable "bastion_access" {
  description = "cidr from where the bastion can be sshed into. Default is ANYWHERE and equivalent to 0.0.0.0/0"
  default     = "ANYWHERE"
}

variable "enable_instance_principal" {
  description = "enable the bastion hosts to call OCI API services without requiring api key"
  default     = false
}

variable "image_ocid" {
  default = "NONE"
}

variable "image_operating_system" {
  # values = Oracle Linux, CentOS, Canonical Ubuntu
  default     = "Oracle Linux"
  description = "operating system to use for the bastion"
}

variable "image_operating_system_version" {
  # Versions of available operating systems can be found here: https://docs.cloud.oracle.com/iaas/images/
  default     = "7.7"
  description = "version of selected operating system"
}

# availability domains
variable "availability_domains" {
  description = "ADs where to provision compute resources"
  type        = "map"

  default = {
    bastion = 1
    gitlab  = 1
  }
}

# bastion packages
variable "bastion_package_update" {
  description = "Update apt database on first boot if bastion host uses Ubuntu as Linux distribution"
  type        = bool
  default     = true
}
variable "bastion_package_upgrade" {
  description = "Upgrade the instance on first boot"
  type        = bool
  default     = true
}
----

. Initialize your base module variables in the locals.tf file:

+
----
locals {
  oci_base_identity = {
    api_fingerprint      = var.api_fingerprint
    api_private_key_path = var.api_private_key_path
    compartment_name     = var.compartment_name
    compartment_ocid     = var.compartment_ocid
    tenancy_ocid         = var.tenancy_ocid
    user_ocid            = var.user_ocid
  }
  oci_base_ssh_keys = {
    ssh_private_key_path = var.ssh_private_key_path
    ssh_public_key_path  = var.ssh_public_key_path
  }
  oci_base_general = {
    disable_auto_retries = var.disable_auto_retries
    label_prefix         = var.label_prefix
    region               = var.region
  }
  oci_base_vcn = {
    vcn_cidr               = var.vcn_cidr
    vcn_dns_label          = var.vcn_dns_label
    vcn_name               = var.vcn_name
    create_nat_gateway     = var.create_nat_gateway
    nat_gateway_name       = var.nat_gateway_name
    create_service_gateway = var.create_service_gateway
    service_gateway_name   = var.service_gateway_name
  }
  oci_base_bastion = {
    newbits                        = var.newbits["bastion"]
    subnets                        = var.subnets["bastion"]
    bastion_shape                  = var.bastion_shape
    create_bastion                 = var.create_bastion
    bastion_access                 = var.bastion_access
    enable_instance_principal      = var.enable_instance_principal
    image_ocid                     = var.image_ocid
    image_operating_system         = var.image_operating_system
    image_operating_system_version = var.image_operating_system_version
    availability_domains           = var.availability_domains["bastion"]
    bastion_package_update         = var.bastion_package_update
    bastion_package_update         = var.bastion_package_upgrade
  }
}
----

. Define the base module to the main.tf

+
----
module "base" {
  source = "./modules/base"

  # identity
  oci_base_identity = local.oci_base_identity

  # ssh keys
  oci_base_ssh_keys = local.oci_base_ssh_keys

  # general oci parameters
  oci_base_general = local.oci_base_general

  # vcn parameters
  oci_base_vcn = local.oci_base_vcn

  # bastion parameters
  oci_base_bastion = local.oci_base_bastion
}
----